export const ACTION_TYPES = {
    GET_TOVARS_START:'GET_TOVARS_START',
    GET_TOVARS_SUCCESS:'GET_TOVARS_SUCCESS',
    GET_TOVARS_FAILURE:'GET_TOVARS_FAILURE',


    GET_FULL_LIST_TOVARS_START:'GET_FULL_LIST_TOVARS',
    GET_FULL_LIST_TOVARS_SUCCESS:'GET_FULL_LIST_TOVARS_SUCCES',
    GET_FULL_LIST_TOVARS_FAILURE:'GET_FULL_LIST_TOVARS_FAILURE',

    GET_FULL_INFO_TOVAR_START:'GET_FULL_INFO_TOVAR_START',
    GET_FULL_INFO_TOVAR_SUCCESS:'GET_FULL_INFO_TOVAR_SUCCESS',
    GET_FULL_INFO_TOVAR_FAILURE:'GET_FULL_INFO_TOVAR_FAILURE',

    SEND_TOVAR_BASCET_START:'SEND_TOVAR_BASCET_START',
    SEND_TOVAR_BASCET_SUCCESS:'SEND_TOVAR_BASCET_SUCCESS',
    SEND_TOVAR_BASCET_FAILURE:'SEND_TOVAR_BASCET_FAILURE',


    GET_TYPES_START:'GET_TYPES_START',
    GET_TYPES_SUCCESS:'GET_TYPES_SUCCESS',
    GET_TYPES_FAILURE:'GET_TYPES_FAILURE',

    ADD_TYPE_START:' ADD_TYPE_START',
    ADD_TYPE_SUCCESS:'ADD_TYPE_SUCCESS',
    ADD_TYPE_FAILURE:'ADD_TYPE_FAILURE',

    ADD_NEW_DEVICE_START:'ADD_NEW_DEVICE_START',
    ADD_NEW_DEVICE_SUCCESS:'ADD_NEW_DEVICE_SUCCESS',
    ADD_NEW_DEVICE_FAILURE:'ADD_NEW_DEVICE_FAILURE'

}